name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Validate Terraform
      run: terraform validate

    - name: Apply Terraform
      run: terraform apply -auto-approve

    - name: Build Docker Image
      run: |
        docker build -t employee-info-frontend .
        docker tag employee-info-frontend:latest <ecr_repo>:latest

    - name: Push Docker Image
      run: |
        aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin <ecr_repo>
        docker push <ecr_repo>:latest
